// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteKeyworks.Cadastros.Infra.Dados.Contextos;

#nullable disable

namespace TesteKeyworks.Cadastros.Infra.Dados.Migrations
{
    [DbContext(typeof(DbKeyworks))]
    partial class DbKeyworksModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesteKeyworks.Cadastros.Dominios.Entidades.Clientes.Cliente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<int>("CodigoMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_material");

                    b.Property<string>("DDI")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("ddi");

                    b.Property<int>("PlantaId")
                        .HasColumnType("integer")
                        .HasColumnName("planta_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(140)")
                        .HasColumnName("razao_social");

                    b.Property<string>("ResponsavelEmail")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("responsavel_email");

                    b.Property<string>("ResponsavelNome")
                        .IsRequired()
                        .HasColumnType("varchar(140)")
                        .HasColumnName("responsavel_nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("Codigo");

                    b.ToTable("clientes", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
